### ISSUE TITLE
Error in a dedicate server

### ISSUE THREAD

**Issue by iccarusA** [iLexiconn/LLibrary#130] opened 2019-03-09 09:05 UTC
I try the mod in my single player, but when I try in the dedicate server crash

crash report
https://pastebin.com/raw/kX8vJc87

**Comment by Gegy** [comment] 2019-03-09 10:43
Hey, this is a duplicate of #129. This is a Bewitchment issue, not LLibrary. It seems that you have an indev version installed, which will not work.

**Closed as completed** 2019-03-10 07:38 UTC
