### ISSUE TITLE
Evil Notch Lib Conflict

### ISSUE THREAD

**Issue by jredfox** [iLexiconn/LLibrary#101] opened 2018-11-25 18:09 UTC
Location:
--
06:07:29 | game |   | info | net/minecraftforge/client/ForgeHooksClient.invalidateLog4jThreadCache()V @65: invokeinterface
06:07:29 | game |   | info | Reason:
06:07:29 | game |   | info | Type 'java/lang/Object' (current frame, stack[2]) is not assignable to 'java/lang/Throwable'

What are you doing to the method are you adding a throwable in memory? I replaced the middle click method but, didn't add a throwable I can do that so we are able to run together but, I want to know why your doing it rather then just adding a try/catch block?

**Comment by Gegy** [comment] 2018-11-25 18:11
LLibrary doesn't touch anything relating to the middle click method.

**Comment by jredfox** [comment] 2018-11-25 18:12
Well All I can say is when our asm runs together it crashes specifically on forge hooks client. I could look to see if I edit/replace anything else but, I don't assume I do.

does later versions of forge make the pick block event throwable in later versions? If not you have to be editing the method somewhere because the crash report isn't wrong.

**Comment by Gegy** [comment] 2018-11-25 18:14
That's very odd. LLibrary, in theory, shouldn't touch any other methods that aren't explicitly patched. While we are patching ForgeHooksClient, the method you mention specifically is not. Are there perhaps any other LLibrary-dependent mods installed that could be doing that?

**Comment by jredfox** [comment] 2018-11-25 18:14
I can reproduce with just llib and evil notch lib. I will look more into it later as for know I am trying to archive stuff for the mc archive.

**Comment by Gegy** [comment] 2018-12-02 10:38
Duplicate of #100

**Closed as completed by Gegy** 2018-12-02 10:38 UTC
