### ISSUE TITLE
Incompatible with The Betweenlands

### ISSUE THREAD

**Issue by Sunconure11** [iLexiconn/LLibrary#92] opened 2018-08-05 18:06 UTC
https://github.com/Angry-Pixel/The-Betweenlands/issues/682

**Comment by pau101** [comment] 2018-08-06 03:54
Thanks for the report! This happens to be a duplicate of #90.

**Closed as completed** 2018-08-06 03:55 UTC
Labels: duplicate

**Comment by Gegy** [comment] 2018-08-06 06:34
1.7.15 re-released with fix. :)
