### ISSUE TITLE
Crash caused by missing class

### ISSUE THREAD

**Issue by Sunconure11** [iLexiconn/LLibrary#106] opened 2018-12-05 23:48 UTC
https://paste.dimdev.org/asakocolev.mccrash

**Comment by Gegy** [comment] 2018-12-06 05:40
Can you send a full log? This can only happen if the contained core jar does not get extracted, which it definitely should.

**Comment by Sunconure11** [comment] 2018-12-06 05:58
I'll try shortly, I'm trying some things to deal with an unrelated bug.

**Comment by Sunconure11** [comment] 2018-12-07 09:58
Unfortunately, I lost said log, as I tried to test something else.

**Comment by Gegy** [comment] 2018-12-07 10:06
Are you unable to reproduce it? If so, I'll close this issue.

**Comment by Sunconure11** [comment] 2018-12-07 10:19
I am no longer able to reproduce it. Instead, I'm getting an unrelated crash on my server.

https://github.com/Shadows-of-Fire/Plants/issues/109

**Comment by eehunter** [comment] 2019-02-07 01:01
I have the same problem in the eclipse testing environment. Here is the log: [https://pastebin.com/tLkXBhMT](url)

**Comment by Gegy** [comment] 2019-02-07 05:23
@eehunter How are you including LLibrary as a dep?

**Comment by eehunter** [comment] 2019-02-08 00:41
here is build.gradle: https://pastebin.com/waKzAL3c

**Comment by Gegy** [comment] 2019-02-08 04:51
Including LLibrary as a jar like that won't properly work within a dev environment. Yo could either use the dev jar or compile with a proper gradle dependency like: `deobfCompile 'net.ilexiconn:llibrary:1.7.17-1.12.2'`

**Comment by eehunter** [comment] 2019-02-09 15:53
Thank you. Also, is there an easy way to do the same with ice and fire?

**Comment by Gegy** [comment] 2019-02-09 15:54
As far as I know, no. IaF isn't hosted on any maven.

**Closed as completed** 2019-02-09 15:54 UTC

**Comment by eehunter** [comment] 2019-02-09 16:12
never mind, that works normally
