### ISSUE TITLE
LLibrary crashes when using Forge 1.12.2-14.23.5.2795

### ISSUE THREAD

**Issue by CammiePone** [iLexiconn/LLibrary#104] opened 2018-12-02 21:22 UTC
> [16:20:38] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[16:20:38] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[16:20:38] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[16:20:38] [main/INFO]: Forge Mod Loader version 14.23.5.2795 for Minecraft 1.12.2 loading
[16:20:38] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Users\Lily\Documents\Curse\Minecraft\Install\runtime\jre-x64\1.8.0_51
[16:20:38] [main/INFO]: Searching C:\Users\Lily\Documents\Curse\Minecraft\Instances\blep\mods for mods
[16:20:38] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:20:38] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[16:20:38] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:20:38] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:20:38] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:20:41] [main/INFO]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[16:20:41] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[16:20:41] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:20:41] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[16:20:42] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:20:42] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[16:20:42] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[16:20:42] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[16:20:45] [main/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/minecraftforge/client/ForgeHooksClient.invalidateLog4jThreadCache()V @65: invokeinterface
  Reason:
    Type 'java/lang/Object' (current frame, stack[2]) is not assignable to 'java/lang/Throwable'
  Current Frame:
    bci: @65
    flags: { }
    locals: { 'java/lang/Object' }
    stack: { 'org/apache/logging/log4j/Logger', 'java/lang/String', 'java/lang/Object' }
  Bytecode:
    0x0000000: 1305 d613 05d8 b605 dc4b 1305 de13 05e0
    0x0000010: b605 dc4c 2a04 b605 e62b 04b6 05e6 2a01
    0x0000020: b605 e7c0 0124 01b6 0128 2b01 b605 e7c0
    0x0000030: 0124 01b6 0128 a700 104b b202 eb13 05eb
    0x0000040: 2ab9 05ef 0300 b1                      
  Exception Handler Table:
    bci [0, 54] => handler: 57
    bci [0, 54] => handler: 57
  Stackmap Table:
    same_locals_1_stack_item_frame(@57,Object[#4])
    append_frame(@70,Object[#4])

	at net.minecraft.client.Minecraft.<init>(Minecraft.java:335) ~[bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) ~[Main.class:?]
	... 6 more
[16:20:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[16:20:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[16:20:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[16:20:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[16:20:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
[16:20:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[16:20:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

LLibrary version: 1.7.15

**Comment by brisingraerowing** [comment] 2018-12-02 22:28
Duplicate of #100. Caused by a change in Forge 2779.

**Closed as completed** 2018-12-03 06:42 UTC

**Comment by Sunconure11** [comment] 2018-12-06 04:07
https://github.com/Chisel-Team/ConnectedTexturesMod/issues/84
